//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restore_Zadohin3IS_24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public Cheque()
        {
            this.ChequePosition = new HashSet<ChequePosition>();
        }
    
        public int ChequeId { get; set; }
        public string Title { get; set; }
        public decimal TotalCost { get; set; }
        public bool IsClosed { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public int WaiterId { get; set; }
        public int TableId { get; set; }
    
        public virtual Table Table { get; set; }
        public virtual Waiter Waiter { get; set; }
        public virtual ICollection<ChequePosition> ChequePosition { get; set; }
    }
}
