//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restore_Zadohin3IS_24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequePosition
    {
        public int ChequePositionId { get; set; }
        public int ChequeId { get; set; }
        public int PositionId { get; set; }
    
        public virtual Cheque Cheque { get; set; }
        public virtual Position Position { get; set; }
    }
}
