//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restore_Zadohin3IS_24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int WaiterId { get; set; }
        public string Name { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<Cheque> Cheque { get; set; }
        public virtual Role Role { get; set; }
    }
}
