//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restore_Zadohin3IS_24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int GuestId { get; set; }
        public string FIO { get; set; }
        public decimal Discont { get; set; }
        public string TelephoneNumber { get; set; }
    }
}
