//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restore_Zadohin3IS_24.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftAccounting
    {
        public ShiftAccounting()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int IDAccount { get; set; }
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public decimal Revenue { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
