//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorizathion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.ChequePosition = new HashSet<ChequePosition>();
        }
    
        public int PositionId { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
        public int CategoryId { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<ChequePosition> ChequePosition { get; set; }
    }
}
