//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorizathion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int TableId { get; set; }
        public string Title { get; set; }
        public int NumberOfVisitors { get; set; }
        public string Description { get; set; }
        public bool IsFree { get; set; }
    
        public virtual ICollection<Cheque> Cheque { get; set; }
    }
}
