//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorizathion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiter
    {
        public Waiter()
        {
            this.Cheque = new HashSet<Cheque>();
        }
    
        public int WaiterId { get; set; }
        public string Name { get; set; }
        public string Pincode { get; set; }
    
        public virtual ICollection<Cheque> Cheque { get; set; }
    }
}
